site_name: react-jsonschema-form documentation
docs_dir: docs
theme: readthedocs

nav:
  - Introduction: index.md
  - Tutorial: tutorial.md
  - Usage:
    - JSON Schema: usage/schema.md
    - uiSchema: usage/uiSchema.md
    - Using widgets: usage/widgets.md
    - "&lt;Form /&gt;": usage/form-props.md
  - Advanced Customization:
    - Custom Widgets and Fields: advanced-customization/custom-widgets-fields.md
    - Custom Templates: advanced-customization/custom-templates.md
    - Theme Customization: advanced-customization/theme-customization.md
    - Other Internals: advanced-customization/internals.md
  - Contributing: contributing.md

markdown_extensions:
  - toc:
      permalink: true
